export default {
    FIND_ALL_CATEGORIES: '/api/open/category/findAllCategories',
    FIND_LOCATION_WISE: '/api/open/getSchoolsLocationWise',
    FEED_LOCATION_WISE: '/api/open/feed/getFeeds',
    GET_LOCALITIES_BY_COUNTRY_ID: '/api/open/location/getLocalitiesByCountryId',
    GET_SUBLOCALITIES1_BY_LOCALITY_ID: '/api/open/location/getSubLocalities1ByLocalityId',
    GET_EP_BASED_ON_SUBLOCALITY_LEVEL_1: '/api/open/getEPSubLocality1Wise',
    SIGN_IN_BY_FIREBASE_UID: '/api/open/user/signInByFirebaseUid',
    GET_ALL_CUNTRIES: '/api/open/location/getCountries',
    GET_FORM_DATA_FOR_SCHOOL: '/api/client/addPlace/getSchoolFormData',
    GET_REVERSE_GEOCODE:'/api/client/location/reverseGeocode',
    GET_AUTOCOMPLETE_RESULTS:'/api/client/location/getAutocompleteResults',
    GET_PLACE_DETAILS_PACE_ID:'/api/client/location/getPlaceDetailsFromPlaceId',
    POST_SCHOOL_DETAIL:'/api/client/addPlace/submitSchool',
    GET_EP_BY_ID: '/api/open/getEPById',
    GET_USER_BY_PUBLIC_ID:'/api/open/user/getUserByPublicId',
    GET_PLACES_MANAGED:'/api/client/user/getPlacesManagedAdmin',
    GET_PLACE_MANAGED_BY_PLACE_PUBLIC_ID:'/api/client/placeAdmin/getPlacesManagedByPlacePublicId',
    SUBMIT_BLOG:'/api/client/blog/submitBlog',
    GET_BLOGS_BY_PLACE_PUBLIC_ID:'/api/open/blog/getBlogsByPlacePublicId'
}